// Code generated by mockery. DO NOT EDIT.

package pkgmocks

import (
	pkghttp "github.com/JoshuaPangaribuan/payslip/internal/pkg/pkghttp/v1"
	mock "github.com/stretchr/testify/mock"
)

// MockEndpointOption is an autogenerated mock type for the EndpointOption type
type MockEndpointOption struct {
	mock.Mock
}

type MockEndpointOption_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEndpointOption) EXPECT() *MockEndpointOption_Expecter {
	return &MockEndpointOption_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0
func (_m *MockEndpointOption) Execute(_a0 *pkghttp.Endpoint) {
	_m.Called(_a0)
}

// MockEndpointOption_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockEndpointOption_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 *pkghttp.Endpoint
func (_e *MockEndpointOption_Expecter) Execute(_a0 interface{}) *MockEndpointOption_Execute_Call {
	return &MockEndpointOption_Execute_Call{Call: _e.mock.On("Execute", _a0)}
}

func (_c *MockEndpointOption_Execute_Call) Run(run func(_a0 *pkghttp.Endpoint)) *MockEndpointOption_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*pkghttp.Endpoint))
	})
	return _c
}

func (_c *MockEndpointOption_Execute_Call) Return() *MockEndpointOption_Execute_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEndpointOption_Execute_Call) RunAndReturn(run func(*pkghttp.Endpoint)) *MockEndpointOption_Execute_Call {
	_c.Run(run)
	return _c
}

// NewMockEndpointOption creates a new instance of MockEndpointOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEndpointOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEndpointOption {
	mock := &MockEndpointOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
