// Code generated by mockery. DO NOT EDIT.

package pkgmocks

import mock "github.com/stretchr/testify/mock"

// MockStatusCodeAware is an autogenerated mock type for the StatusCodeAware type
type MockStatusCodeAware struct {
	mock.Mock
}

type MockStatusCodeAware_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStatusCodeAware) EXPECT() *MockStatusCodeAware_Expecter {
	return &MockStatusCodeAware_Expecter{mock: &_m.Mock}
}

// StatusCode provides a mock function with no fields
func (_m *MockStatusCodeAware) StatusCode() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for StatusCode")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockStatusCodeAware_StatusCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StatusCode'
type MockStatusCodeAware_StatusCode_Call struct {
	*mock.Call
}

// StatusCode is a helper method to define mock.On call
func (_e *MockStatusCodeAware_Expecter) StatusCode() *MockStatusCodeAware_StatusCode_Call {
	return &MockStatusCodeAware_StatusCode_Call{Call: _e.mock.On("StatusCode")}
}

func (_c *MockStatusCodeAware_StatusCode_Call) Run(run func()) *MockStatusCodeAware_StatusCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStatusCodeAware_StatusCode_Call) Return(_a0 int) *MockStatusCodeAware_StatusCode_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStatusCodeAware_StatusCode_Call) RunAndReturn(run func() int) *MockStatusCodeAware_StatusCode_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStatusCodeAware creates a new instance of MockStatusCodeAware. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStatusCodeAware(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStatusCodeAware {
	mock := &MockStatusCodeAware{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
