// Code generated by mockery. DO NOT EDIT.

package pkgmocks

import (
	context "context"
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// MockResponseEncoder is an autogenerated mock type for the ResponseEncoder type
type MockResponseEncoder struct {
	mock.Mock
}

type MockResponseEncoder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockResponseEncoder) EXPECT() *MockResponseEncoder_Expecter {
	return &MockResponseEncoder_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, w, response
func (_m *MockResponseEncoder) Execute(ctx context.Context, w http.ResponseWriter, response interface{}) error {
	ret := _m.Called(ctx, w, response)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, http.ResponseWriter, interface{}) error); ok {
		r0 = rf(ctx, w, response)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockResponseEncoder_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockResponseEncoder_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - w http.ResponseWriter
//   - response interface{}
func (_e *MockResponseEncoder_Expecter) Execute(ctx interface{}, w interface{}, response interface{}) *MockResponseEncoder_Execute_Call {
	return &MockResponseEncoder_Execute_Call{Call: _e.mock.On("Execute", ctx, w, response)}
}

func (_c *MockResponseEncoder_Execute_Call) Run(run func(ctx context.Context, w http.ResponseWriter, response interface{})) *MockResponseEncoder_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(http.ResponseWriter), args[2].(interface{}))
	})
	return _c
}

func (_c *MockResponseEncoder_Execute_Call) Return(_a0 error) *MockResponseEncoder_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockResponseEncoder_Execute_Call) RunAndReturn(run func(context.Context, http.ResponseWriter, interface{}) error) *MockResponseEncoder_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockResponseEncoder creates a new instance of MockResponseEncoder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockResponseEncoder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockResponseEncoder {
	mock := &MockResponseEncoder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
