// Code generated by mockery. DO NOT EDIT.

package pkgmocks

import (
	context "context"

	pkghttp "github.com/JoshuaPangaribuan/payslip/internal/pkg/pkghttp/v1"
	mock "github.com/stretchr/testify/mock"
)

// MockRequestDecoder is an autogenerated mock type for the RequestDecoder type
type MockRequestDecoder struct {
	mock.Mock
}

type MockRequestDecoder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRequestDecoder) EXPECT() *MockRequestDecoder_Expecter {
	return &MockRequestDecoder_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, r
func (_m *MockRequestDecoder) Execute(ctx context.Context, r pkghttp.RequestReadWriter) (context.Context, error) {
	ret := _m.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 context.Context
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pkghttp.RequestReadWriter) (context.Context, error)); ok {
		return rf(ctx, r)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pkghttp.RequestReadWriter) context.Context); ok {
		r0 = rf(ctx, r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pkghttp.RequestReadWriter) error); ok {
		r1 = rf(ctx, r)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRequestDecoder_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockRequestDecoder_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - r pkghttp.RequestReadWriter
func (_e *MockRequestDecoder_Expecter) Execute(ctx interface{}, r interface{}) *MockRequestDecoder_Execute_Call {
	return &MockRequestDecoder_Execute_Call{Call: _e.mock.On("Execute", ctx, r)}
}

func (_c *MockRequestDecoder_Execute_Call) Run(run func(ctx context.Context, r pkghttp.RequestReadWriter)) *MockRequestDecoder_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(pkghttp.RequestReadWriter))
	})
	return _c
}

func (_c *MockRequestDecoder_Execute_Call) Return(_a0 context.Context, _a1 error) *MockRequestDecoder_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRequestDecoder_Execute_Call) RunAndReturn(run func(context.Context, pkghttp.RequestReadWriter) (context.Context, error)) *MockRequestDecoder_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRequestDecoder creates a new instance of MockRequestDecoder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRequestDecoder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRequestDecoder {
	mock := &MockRequestDecoder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
