// Code generated by mockery. DO NOT EDIT.

package pkgmocks

import (
	pkghttp "github.com/JoshuaPangaribuan/payslip/internal/pkg/pkghttp/v1"
	mock "github.com/stretchr/testify/mock"
)

// MockServerOption is an autogenerated mock type for the ServerOption type
type MockServerOption struct {
	mock.Mock
}

type MockServerOption_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServerOption) EXPECT() *MockServerOption_Expecter {
	return &MockServerOption_Expecter{mock: &_m.Mock}
}

// Apply provides a mock function with given fields: _a0
func (_m *MockServerOption) Apply(_a0 *pkghttp.Server) {
	_m.Called(_a0)
}

// MockServerOption_Apply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Apply'
type MockServerOption_Apply_Call struct {
	*mock.Call
}

// Apply is a helper method to define mock.On call
//   - _a0 *pkghttp.Server
func (_e *MockServerOption_Expecter) Apply(_a0 interface{}) *MockServerOption_Apply_Call {
	return &MockServerOption_Apply_Call{Call: _e.mock.On("Apply", _a0)}
}

func (_c *MockServerOption_Apply_Call) Run(run func(_a0 *pkghttp.Server)) *MockServerOption_Apply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*pkghttp.Server))
	})
	return _c
}

func (_c *MockServerOption_Apply_Call) Return() *MockServerOption_Apply_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServerOption_Apply_Call) RunAndReturn(run func(*pkghttp.Server)) *MockServerOption_Apply_Call {
	_c.Run(run)
	return _c
}

// NewMockServerOption creates a new instance of MockServerOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServerOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServerOption {
	mock := &MockServerOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
