// Code generated by mockery. DO NOT EDIT.

package pkgmocks

import (
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockUUID is an autogenerated mock type for the UUID type
type MockUUID struct {
	mock.Mock
}

type MockUUID_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUUID) EXPECT() *MockUUID_Expecter {
	return &MockUUID_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function with no fields
func (_m *MockUUID) Generate() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockUUID_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type MockUUID_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
func (_e *MockUUID_Expecter) Generate() *MockUUID_Generate_Call {
	return &MockUUID_Generate_Call{Call: _e.mock.On("Generate")}
}

func (_c *MockUUID_Generate_Call) Run(run func()) *MockUUID_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUUID_Generate_Call) Return(_a0 string) *MockUUID_Generate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUUID_Generate_Call) RunAndReturn(run func() string) *MockUUID_Generate_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateV4 provides a mock function with no fields
func (_m *MockUUID) GenerateV4() uuid.UUID {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GenerateV4")
	}

	var r0 uuid.UUID
	if rf, ok := ret.Get(0).(func() uuid.UUID); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	return r0
}

// MockUUID_GenerateV4_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateV4'
type MockUUID_GenerateV4_Call struct {
	*mock.Call
}

// GenerateV4 is a helper method to define mock.On call
func (_e *MockUUID_Expecter) GenerateV4() *MockUUID_GenerateV4_Call {
	return &MockUUID_GenerateV4_Call{Call: _e.mock.On("GenerateV4")}
}

func (_c *MockUUID_GenerateV4_Call) Run(run func()) *MockUUID_GenerateV4_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUUID_GenerateV4_Call) Return(_a0 uuid.UUID) *MockUUID_GenerateV4_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUUID_GenerateV4_Call) RunAndReturn(run func() uuid.UUID) *MockUUID_GenerateV4_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUUID creates a new instance of MockUUID. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUUID(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUUID {
	mock := &MockUUID{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
