// Code generated by mockery. DO NOT EDIT.

package payslipmocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	sqlentity "github.com/JoshuaPangaribuan/payslip/internal/payslip/internal/entity/sqlentity"

	time "time"

	uuid "github.com/google/uuid"
)

// MockPayrollSummaryRepository is an autogenerated mock type for the PayrollSummaryRepository type
type MockPayrollSummaryRepository struct {
	mock.Mock
}

type MockPayrollSummaryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPayrollSummaryRepository) EXPECT() *MockPayrollSummaryRepository_Expecter {
	return &MockPayrollSummaryRepository_Expecter{mock: &_m.Mock}
}

// GetActiveEmployees provides a mock function with given fields: ctx
func (_m *MockPayrollSummaryRepository) GetActiveEmployees(ctx context.Context) ([]*sqlentity.Employees, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveEmployees")
	}

	var r0 []*sqlentity.Employees
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*sqlentity.Employees, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*sqlentity.Employees); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*sqlentity.Employees)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPayrollSummaryRepository_GetActiveEmployees_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveEmployees'
type MockPayrollSummaryRepository_GetActiveEmployees_Call struct {
	*mock.Call
}

// GetActiveEmployees is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPayrollSummaryRepository_Expecter) GetActiveEmployees(ctx interface{}) *MockPayrollSummaryRepository_GetActiveEmployees_Call {
	return &MockPayrollSummaryRepository_GetActiveEmployees_Call{Call: _e.mock.On("GetActiveEmployees", ctx)}
}

func (_c *MockPayrollSummaryRepository_GetActiveEmployees_Call) Run(run func(ctx context.Context)) *MockPayrollSummaryRepository_GetActiveEmployees_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockPayrollSummaryRepository_GetActiveEmployees_Call) Return(_a0 []*sqlentity.Employees, _a1 error) *MockPayrollSummaryRepository_GetActiveEmployees_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPayrollSummaryRepository_GetActiveEmployees_Call) RunAndReturn(run func(context.Context) ([]*sqlentity.Employees, error)) *MockPayrollSummaryRepository_GetActiveEmployees_Call {
	_c.Call.Return(run)
	return _c
}

// GetAttendanceByPeriod provides a mock function with given fields: ctx, employeeID, startDate, endDate
func (_m *MockPayrollSummaryRepository) GetAttendanceByPeriod(ctx context.Context, employeeID uuid.UUID, startDate time.Time, endDate time.Time) ([]*sqlentity.AttendanceRecords, error) {
	ret := _m.Called(ctx, employeeID, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetAttendanceByPeriod")
	}

	var r0 []*sqlentity.AttendanceRecords
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, time.Time) ([]*sqlentity.AttendanceRecords, error)); ok {
		return rf(ctx, employeeID, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, time.Time) []*sqlentity.AttendanceRecords); ok {
		r0 = rf(ctx, employeeID, startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*sqlentity.AttendanceRecords)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time, time.Time) error); ok {
		r1 = rf(ctx, employeeID, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPayrollSummaryRepository_GetAttendanceByPeriod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAttendanceByPeriod'
type MockPayrollSummaryRepository_GetAttendanceByPeriod_Call struct {
	*mock.Call
}

// GetAttendanceByPeriod is a helper method to define mock.On call
//   - ctx context.Context
//   - employeeID uuid.UUID
//   - startDate time.Time
//   - endDate time.Time
func (_e *MockPayrollSummaryRepository_Expecter) GetAttendanceByPeriod(ctx interface{}, employeeID interface{}, startDate interface{}, endDate interface{}) *MockPayrollSummaryRepository_GetAttendanceByPeriod_Call {
	return &MockPayrollSummaryRepository_GetAttendanceByPeriod_Call{Call: _e.mock.On("GetAttendanceByPeriod", ctx, employeeID, startDate, endDate)}
}

func (_c *MockPayrollSummaryRepository_GetAttendanceByPeriod_Call) Run(run func(ctx context.Context, employeeID uuid.UUID, startDate time.Time, endDate time.Time)) *MockPayrollSummaryRepository_GetAttendanceByPeriod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time), args[3].(time.Time))
	})
	return _c
}

func (_c *MockPayrollSummaryRepository_GetAttendanceByPeriod_Call) Return(_a0 []*sqlentity.AttendanceRecords, _a1 error) *MockPayrollSummaryRepository_GetAttendanceByPeriod_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPayrollSummaryRepository_GetAttendanceByPeriod_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time, time.Time) ([]*sqlentity.AttendanceRecords, error)) *MockPayrollSummaryRepository_GetAttendanceByPeriod_Call {
	_c.Call.Return(run)
	return _c
}

// GetAttendancePeriod provides a mock function with given fields: ctx, attendancePeriodID
func (_m *MockPayrollSummaryRepository) GetAttendancePeriod(ctx context.Context, attendancePeriodID uuid.UUID) (*sqlentity.AttendancePeriods, error) {
	ret := _m.Called(ctx, attendancePeriodID)

	if len(ret) == 0 {
		panic("no return value specified for GetAttendancePeriod")
	}

	var r0 *sqlentity.AttendancePeriods
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*sqlentity.AttendancePeriods, error)); ok {
		return rf(ctx, attendancePeriodID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *sqlentity.AttendancePeriods); ok {
		r0 = rf(ctx, attendancePeriodID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqlentity.AttendancePeriods)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, attendancePeriodID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPayrollSummaryRepository_GetAttendancePeriod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAttendancePeriod'
type MockPayrollSummaryRepository_GetAttendancePeriod_Call struct {
	*mock.Call
}

// GetAttendancePeriod is a helper method to define mock.On call
//   - ctx context.Context
//   - attendancePeriodID uuid.UUID
func (_e *MockPayrollSummaryRepository_Expecter) GetAttendancePeriod(ctx interface{}, attendancePeriodID interface{}) *MockPayrollSummaryRepository_GetAttendancePeriod_Call {
	return &MockPayrollSummaryRepository_GetAttendancePeriod_Call{Call: _e.mock.On("GetAttendancePeriod", ctx, attendancePeriodID)}
}

func (_c *MockPayrollSummaryRepository_GetAttendancePeriod_Call) Run(run func(ctx context.Context, attendancePeriodID uuid.UUID)) *MockPayrollSummaryRepository_GetAttendancePeriod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockPayrollSummaryRepository_GetAttendancePeriod_Call) Return(_a0 *sqlentity.AttendancePeriods, _a1 error) *MockPayrollSummaryRepository_GetAttendancePeriod_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPayrollSummaryRepository_GetAttendancePeriod_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*sqlentity.AttendancePeriods, error)) *MockPayrollSummaryRepository_GetAttendancePeriod_Call {
	_c.Call.Return(run)
	return _c
}

// GetOvertimeByPeriod provides a mock function with given fields: ctx, employeeID, startDate, endDate
func (_m *MockPayrollSummaryRepository) GetOvertimeByPeriod(ctx context.Context, employeeID uuid.UUID, startDate time.Time, endDate time.Time) ([]*sqlentity.OvertimeRequests, error) {
	ret := _m.Called(ctx, employeeID, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetOvertimeByPeriod")
	}

	var r0 []*sqlentity.OvertimeRequests
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, time.Time) ([]*sqlentity.OvertimeRequests, error)); ok {
		return rf(ctx, employeeID, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, time.Time) []*sqlentity.OvertimeRequests); ok {
		r0 = rf(ctx, employeeID, startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*sqlentity.OvertimeRequests)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time, time.Time) error); ok {
		r1 = rf(ctx, employeeID, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPayrollSummaryRepository_GetOvertimeByPeriod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOvertimeByPeriod'
type MockPayrollSummaryRepository_GetOvertimeByPeriod_Call struct {
	*mock.Call
}

// GetOvertimeByPeriod is a helper method to define mock.On call
//   - ctx context.Context
//   - employeeID uuid.UUID
//   - startDate time.Time
//   - endDate time.Time
func (_e *MockPayrollSummaryRepository_Expecter) GetOvertimeByPeriod(ctx interface{}, employeeID interface{}, startDate interface{}, endDate interface{}) *MockPayrollSummaryRepository_GetOvertimeByPeriod_Call {
	return &MockPayrollSummaryRepository_GetOvertimeByPeriod_Call{Call: _e.mock.On("GetOvertimeByPeriod", ctx, employeeID, startDate, endDate)}
}

func (_c *MockPayrollSummaryRepository_GetOvertimeByPeriod_Call) Run(run func(ctx context.Context, employeeID uuid.UUID, startDate time.Time, endDate time.Time)) *MockPayrollSummaryRepository_GetOvertimeByPeriod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time), args[3].(time.Time))
	})
	return _c
}

func (_c *MockPayrollSummaryRepository_GetOvertimeByPeriod_Call) Return(_a0 []*sqlentity.OvertimeRequests, _a1 error) *MockPayrollSummaryRepository_GetOvertimeByPeriod_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPayrollSummaryRepository_GetOvertimeByPeriod_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time, time.Time) ([]*sqlentity.OvertimeRequests, error)) *MockPayrollSummaryRepository_GetOvertimeByPeriod_Call {
	_c.Call.Return(run)
	return _c
}

// GetPayrollRun provides a mock function with given fields: ctx, payrollRunID
func (_m *MockPayrollSummaryRepository) GetPayrollRun(ctx context.Context, payrollRunID uuid.UUID) (*sqlentity.PayrollRuns, error) {
	ret := _m.Called(ctx, payrollRunID)

	if len(ret) == 0 {
		panic("no return value specified for GetPayrollRun")
	}

	var r0 *sqlentity.PayrollRuns
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*sqlentity.PayrollRuns, error)); ok {
		return rf(ctx, payrollRunID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *sqlentity.PayrollRuns); ok {
		r0 = rf(ctx, payrollRunID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqlentity.PayrollRuns)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, payrollRunID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPayrollSummaryRepository_GetPayrollRun_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPayrollRun'
type MockPayrollSummaryRepository_GetPayrollRun_Call struct {
	*mock.Call
}

// GetPayrollRun is a helper method to define mock.On call
//   - ctx context.Context
//   - payrollRunID uuid.UUID
func (_e *MockPayrollSummaryRepository_Expecter) GetPayrollRun(ctx interface{}, payrollRunID interface{}) *MockPayrollSummaryRepository_GetPayrollRun_Call {
	return &MockPayrollSummaryRepository_GetPayrollRun_Call{Call: _e.mock.On("GetPayrollRun", ctx, payrollRunID)}
}

func (_c *MockPayrollSummaryRepository_GetPayrollRun_Call) Run(run func(ctx context.Context, payrollRunID uuid.UUID)) *MockPayrollSummaryRepository_GetPayrollRun_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockPayrollSummaryRepository_GetPayrollRun_Call) Return(_a0 *sqlentity.PayrollRuns, _a1 error) *MockPayrollSummaryRepository_GetPayrollRun_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPayrollSummaryRepository_GetPayrollRun_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*sqlentity.PayrollRuns, error)) *MockPayrollSummaryRepository_GetPayrollRun_Call {
	_c.Call.Return(run)
	return _c
}

// GetReimbursementsByPeriod provides a mock function with given fields: ctx, employeeID, startDate, endDate
func (_m *MockPayrollSummaryRepository) GetReimbursementsByPeriod(ctx context.Context, employeeID uuid.UUID, startDate time.Time, endDate time.Time) ([]*sqlentity.ReimbursementRequests, error) {
	ret := _m.Called(ctx, employeeID, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetReimbursementsByPeriod")
	}

	var r0 []*sqlentity.ReimbursementRequests
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, time.Time) ([]*sqlentity.ReimbursementRequests, error)); ok {
		return rf(ctx, employeeID, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, time.Time) []*sqlentity.ReimbursementRequests); ok {
		r0 = rf(ctx, employeeID, startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*sqlentity.ReimbursementRequests)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time, time.Time) error); ok {
		r1 = rf(ctx, employeeID, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPayrollSummaryRepository_GetReimbursementsByPeriod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReimbursementsByPeriod'
type MockPayrollSummaryRepository_GetReimbursementsByPeriod_Call struct {
	*mock.Call
}

// GetReimbursementsByPeriod is a helper method to define mock.On call
//   - ctx context.Context
//   - employeeID uuid.UUID
//   - startDate time.Time
//   - endDate time.Time
func (_e *MockPayrollSummaryRepository_Expecter) GetReimbursementsByPeriod(ctx interface{}, employeeID interface{}, startDate interface{}, endDate interface{}) *MockPayrollSummaryRepository_GetReimbursementsByPeriod_Call {
	return &MockPayrollSummaryRepository_GetReimbursementsByPeriod_Call{Call: _e.mock.On("GetReimbursementsByPeriod", ctx, employeeID, startDate, endDate)}
}

func (_c *MockPayrollSummaryRepository_GetReimbursementsByPeriod_Call) Run(run func(ctx context.Context, employeeID uuid.UUID, startDate time.Time, endDate time.Time)) *MockPayrollSummaryRepository_GetReimbursementsByPeriod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time), args[3].(time.Time))
	})
	return _c
}

func (_c *MockPayrollSummaryRepository_GetReimbursementsByPeriod_Call) Return(_a0 []*sqlentity.ReimbursementRequests, _a1 error) *MockPayrollSummaryRepository_GetReimbursementsByPeriod_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPayrollSummaryRepository_GetReimbursementsByPeriod_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time, time.Time) ([]*sqlentity.ReimbursementRequests, error)) *MockPayrollSummaryRepository_GetReimbursementsByPeriod_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPayrollSummaryRepository creates a new instance of MockPayrollSummaryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPayrollSummaryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPayrollSummaryRepository {
	mock := &MockPayrollSummaryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
