// Code generated by mockery. DO NOT EDIT.

package payslipmocks

import (
	context "context"

	usecases "github.com/JoshuaPangaribuan/payslip/internal/payslip/internal/usecases"
	mock "github.com/stretchr/testify/mock"
)

// MockAdminAddAttendancePeriodUsecase is an autogenerated mock type for the AdminAddAttendancePeriodUsecase type
type MockAdminAddAttendancePeriodUsecase struct {
	mock.Mock
}

type MockAdminAddAttendancePeriodUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAdminAddAttendancePeriodUsecase) EXPECT() *MockAdminAddAttendancePeriodUsecase_Expecter {
	return &MockAdminAddAttendancePeriodUsecase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, input
func (_m *MockAdminAddAttendancePeriodUsecase) Execute(ctx context.Context, input usecases.AdminAddAttendancePeriodInput) (usecases.AdminAddAttendancePeriodOutput, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 usecases.AdminAddAttendancePeriodOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usecases.AdminAddAttendancePeriodInput) (usecases.AdminAddAttendancePeriodOutput, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usecases.AdminAddAttendancePeriodInput) usecases.AdminAddAttendancePeriodOutput); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(usecases.AdminAddAttendancePeriodOutput)
	}

	if rf, ok := ret.Get(1).(func(context.Context, usecases.AdminAddAttendancePeriodInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdminAddAttendancePeriodUsecase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockAdminAddAttendancePeriodUsecase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - input usecases.AdminAddAttendancePeriodInput
func (_e *MockAdminAddAttendancePeriodUsecase_Expecter) Execute(ctx interface{}, input interface{}) *MockAdminAddAttendancePeriodUsecase_Execute_Call {
	return &MockAdminAddAttendancePeriodUsecase_Execute_Call{Call: _e.mock.On("Execute", ctx, input)}
}

func (_c *MockAdminAddAttendancePeriodUsecase_Execute_Call) Run(run func(ctx context.Context, input usecases.AdminAddAttendancePeriodInput)) *MockAdminAddAttendancePeriodUsecase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usecases.AdminAddAttendancePeriodInput))
	})
	return _c
}

func (_c *MockAdminAddAttendancePeriodUsecase_Execute_Call) Return(_a0 usecases.AdminAddAttendancePeriodOutput, _a1 error) *MockAdminAddAttendancePeriodUsecase_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdminAddAttendancePeriodUsecase_Execute_Call) RunAndReturn(run func(context.Context, usecases.AdminAddAttendancePeriodInput) (usecases.AdminAddAttendancePeriodOutput, error)) *MockAdminAddAttendancePeriodUsecase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAdminAddAttendancePeriodUsecase creates a new instance of MockAdminAddAttendancePeriodUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAdminAddAttendancePeriodUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAdminAddAttendancePeriodUsecase {
	mock := &MockAdminAddAttendancePeriodUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
