// Code generated by mockery. DO NOT EDIT.

package payslipmocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	sqlentity "github.com/JoshuaPangaribuan/payslip/internal/payslip/internal/entity/sqlentity"
)

// MockEmployeeRepository is an autogenerated mock type for the EmployeeRepository type
type MockEmployeeRepository struct {
	mock.Mock
}

type MockEmployeeRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEmployeeRepository) EXPECT() *MockEmployeeRepository_Expecter {
	return &MockEmployeeRepository_Expecter{mock: &_m.Mock}
}

// GetByUsername provides a mock function with given fields: ctx, username
func (_m *MockEmployeeRepository) GetByUsername(ctx context.Context, username string) (*sqlentity.Employees, error) {
	ret := _m.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for GetByUsername")
	}

	var r0 *sqlentity.Employees
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*sqlentity.Employees, error)); ok {
		return rf(ctx, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *sqlentity.Employees); ok {
		r0 = rf(ctx, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqlentity.Employees)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEmployeeRepository_GetByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUsername'
type MockEmployeeRepository_GetByUsername_Call struct {
	*mock.Call
}

// GetByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockEmployeeRepository_Expecter) GetByUsername(ctx interface{}, username interface{}) *MockEmployeeRepository_GetByUsername_Call {
	return &MockEmployeeRepository_GetByUsername_Call{Call: _e.mock.On("GetByUsername", ctx, username)}
}

func (_c *MockEmployeeRepository_GetByUsername_Call) Run(run func(ctx context.Context, username string)) *MockEmployeeRepository_GetByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockEmployeeRepository_GetByUsername_Call) Return(_a0 *sqlentity.Employees, _a1 error) *MockEmployeeRepository_GetByUsername_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEmployeeRepository_GetByUsername_Call) RunAndReturn(run func(context.Context, string) (*sqlentity.Employees, error)) *MockEmployeeRepository_GetByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEmployeeRepository creates a new instance of MockEmployeeRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmployeeRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmployeeRepository {
	mock := &MockEmployeeRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
