// Code generated by mockery. DO NOT EDIT.

package payslipmocks

import (
	context "context"

	usecases "github.com/JoshuaPangaribuan/payslip/internal/payslip/internal/usecases"
	mock "github.com/stretchr/testify/mock"
)

// MockEmployeeLoginUsecase is an autogenerated mock type for the EmployeeLoginUsecase type
type MockEmployeeLoginUsecase struct {
	mock.Mock
}

type MockEmployeeLoginUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEmployeeLoginUsecase) EXPECT() *MockEmployeeLoginUsecase_Expecter {
	return &MockEmployeeLoginUsecase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, in
func (_m *MockEmployeeLoginUsecase) Execute(ctx context.Context, in usecases.EmployeeLoginInput) (usecases.EmployeeLoginOutput, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 usecases.EmployeeLoginOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usecases.EmployeeLoginInput) (usecases.EmployeeLoginOutput, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usecases.EmployeeLoginInput) usecases.EmployeeLoginOutput); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Get(0).(usecases.EmployeeLoginOutput)
	}

	if rf, ok := ret.Get(1).(func(context.Context, usecases.EmployeeLoginInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEmployeeLoginUsecase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockEmployeeLoginUsecase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - in usecases.EmployeeLoginInput
func (_e *MockEmployeeLoginUsecase_Expecter) Execute(ctx interface{}, in interface{}) *MockEmployeeLoginUsecase_Execute_Call {
	return &MockEmployeeLoginUsecase_Execute_Call{Call: _e.mock.On("Execute", ctx, in)}
}

func (_c *MockEmployeeLoginUsecase_Execute_Call) Run(run func(ctx context.Context, in usecases.EmployeeLoginInput)) *MockEmployeeLoginUsecase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usecases.EmployeeLoginInput))
	})
	return _c
}

func (_c *MockEmployeeLoginUsecase_Execute_Call) Return(_a0 usecases.EmployeeLoginOutput, _a1 error) *MockEmployeeLoginUsecase_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEmployeeLoginUsecase_Execute_Call) RunAndReturn(run func(context.Context, usecases.EmployeeLoginInput) (usecases.EmployeeLoginOutput, error)) *MockEmployeeLoginUsecase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEmployeeLoginUsecase creates a new instance of MockEmployeeLoginUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmployeeLoginUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmployeeLoginUsecase {
	mock := &MockEmployeeLoginUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
