// Code generated by mockery. DO NOT EDIT.

package payslipmocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	sqlentity "github.com/JoshuaPangaribuan/payslip/internal/payslip/internal/entity/sqlentity"

	time "time"

	uuid "github.com/google/uuid"
)

// MockAttendanceRepository is an autogenerated mock type for the AttendanceRepository type
type MockAttendanceRepository struct {
	mock.Mock
}

type MockAttendanceRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAttendanceRepository) EXPECT() *MockAttendanceRepository_Expecter {
	return &MockAttendanceRepository_Expecter{mock: &_m.Mock}
}

// CreateAttendance provides a mock function with given fields: ctx, attendance
func (_m *MockAttendanceRepository) CreateAttendance(ctx context.Context, attendance *sqlentity.AttendanceRecords) error {
	ret := _m.Called(ctx, attendance)

	if len(ret) == 0 {
		panic("no return value specified for CreateAttendance")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlentity.AttendanceRecords) error); ok {
		r0 = rf(ctx, attendance)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAttendanceRepository_CreateAttendance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAttendance'
type MockAttendanceRepository_CreateAttendance_Call struct {
	*mock.Call
}

// CreateAttendance is a helper method to define mock.On call
//   - ctx context.Context
//   - attendance *sqlentity.AttendanceRecords
func (_e *MockAttendanceRepository_Expecter) CreateAttendance(ctx interface{}, attendance interface{}) *MockAttendanceRepository_CreateAttendance_Call {
	return &MockAttendanceRepository_CreateAttendance_Call{Call: _e.mock.On("CreateAttendance", ctx, attendance)}
}

func (_c *MockAttendanceRepository_CreateAttendance_Call) Run(run func(ctx context.Context, attendance *sqlentity.AttendanceRecords)) *MockAttendanceRepository_CreateAttendance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlentity.AttendanceRecords))
	})
	return _c
}

func (_c *MockAttendanceRepository_CreateAttendance_Call) Return(_a0 error) *MockAttendanceRepository_CreateAttendance_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAttendanceRepository_CreateAttendance_Call) RunAndReturn(run func(context.Context, *sqlentity.AttendanceRecords) error) *MockAttendanceRepository_CreateAttendance_Call {
	_c.Call.Return(run)
	return _c
}

// GetAttendanceByEmployeeAndDate provides a mock function with given fields: ctx, employeeID, date
func (_m *MockAttendanceRepository) GetAttendanceByEmployeeAndDate(ctx context.Context, employeeID uuid.UUID, date time.Time) (*sqlentity.AttendanceRecords, error) {
	ret := _m.Called(ctx, employeeID, date)

	if len(ret) == 0 {
		panic("no return value specified for GetAttendanceByEmployeeAndDate")
	}

	var r0 *sqlentity.AttendanceRecords
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) (*sqlentity.AttendanceRecords, error)); ok {
		return rf(ctx, employeeID, date)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) *sqlentity.AttendanceRecords); ok {
		r0 = rf(ctx, employeeID, date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqlentity.AttendanceRecords)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r1 = rf(ctx, employeeID, date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAttendanceRepository_GetAttendanceByEmployeeAndDate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAttendanceByEmployeeAndDate'
type MockAttendanceRepository_GetAttendanceByEmployeeAndDate_Call struct {
	*mock.Call
}

// GetAttendanceByEmployeeAndDate is a helper method to define mock.On call
//   - ctx context.Context
//   - employeeID uuid.UUID
//   - date time.Time
func (_e *MockAttendanceRepository_Expecter) GetAttendanceByEmployeeAndDate(ctx interface{}, employeeID interface{}, date interface{}) *MockAttendanceRepository_GetAttendanceByEmployeeAndDate_Call {
	return &MockAttendanceRepository_GetAttendanceByEmployeeAndDate_Call{Call: _e.mock.On("GetAttendanceByEmployeeAndDate", ctx, employeeID, date)}
}

func (_c *MockAttendanceRepository_GetAttendanceByEmployeeAndDate_Call) Run(run func(ctx context.Context, employeeID uuid.UUID, date time.Time)) *MockAttendanceRepository_GetAttendanceByEmployeeAndDate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time))
	})
	return _c
}

func (_c *MockAttendanceRepository_GetAttendanceByEmployeeAndDate_Call) Return(_a0 *sqlentity.AttendanceRecords, _a1 error) *MockAttendanceRepository_GetAttendanceByEmployeeAndDate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAttendanceRepository_GetAttendanceByEmployeeAndDate_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time) (*sqlentity.AttendanceRecords, error)) *MockAttendanceRepository_GetAttendanceByEmployeeAndDate_Call {
	_c.Call.Return(run)
	return _c
}

// GetAttendancePeriodByID provides a mock function with given fields: ctx, id
func (_m *MockAttendanceRepository) GetAttendancePeriodByID(ctx context.Context, id uuid.UUID) (*sqlentity.AttendancePeriods, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetAttendancePeriodByID")
	}

	var r0 *sqlentity.AttendancePeriods
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*sqlentity.AttendancePeriods, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *sqlentity.AttendancePeriods); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqlentity.AttendancePeriods)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAttendanceRepository_GetAttendancePeriodByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAttendancePeriodByID'
type MockAttendanceRepository_GetAttendancePeriodByID_Call struct {
	*mock.Call
}

// GetAttendancePeriodByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockAttendanceRepository_Expecter) GetAttendancePeriodByID(ctx interface{}, id interface{}) *MockAttendanceRepository_GetAttendancePeriodByID_Call {
	return &MockAttendanceRepository_GetAttendancePeriodByID_Call{Call: _e.mock.On("GetAttendancePeriodByID", ctx, id)}
}

func (_c *MockAttendanceRepository_GetAttendancePeriodByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockAttendanceRepository_GetAttendancePeriodByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockAttendanceRepository_GetAttendancePeriodByID_Call) Return(_a0 *sqlentity.AttendancePeriods, _a1 error) *MockAttendanceRepository_GetAttendancePeriodByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAttendanceRepository_GetAttendancePeriodByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*sqlentity.AttendancePeriods, error)) *MockAttendanceRepository_GetAttendancePeriodByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAttendanceRepository creates a new instance of MockAttendanceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAttendanceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAttendanceRepository {
	mock := &MockAttendanceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
