// Code generated by mockery. DO NOT EDIT.

package payslipmocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	sqlentity "github.com/JoshuaPangaribuan/payslip/internal/payslip/internal/entity/sqlentity"
)

// MockAuditLogRepository is an autogenerated mock type for the AuditLogRepository type
type MockAuditLogRepository struct {
	mock.Mock
}

type MockAuditLogRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuditLogRepository) EXPECT() *MockAuditLogRepository_Expecter {
	return &MockAuditLogRepository_Expecter{mock: &_m.Mock}
}

// CreateAuditLog provides a mock function with given fields: ctx, log
func (_m *MockAuditLogRepository) CreateAuditLog(ctx context.Context, log *sqlentity.AuditLogs) error {
	ret := _m.Called(ctx, log)

	if len(ret) == 0 {
		panic("no return value specified for CreateAuditLog")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlentity.AuditLogs) error); ok {
		r0 = rf(ctx, log)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuditLogRepository_CreateAuditLog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAuditLog'
type MockAuditLogRepository_CreateAuditLog_Call struct {
	*mock.Call
}

// CreateAuditLog is a helper method to define mock.On call
//   - ctx context.Context
//   - log *sqlentity.AuditLogs
func (_e *MockAuditLogRepository_Expecter) CreateAuditLog(ctx interface{}, log interface{}) *MockAuditLogRepository_CreateAuditLog_Call {
	return &MockAuditLogRepository_CreateAuditLog_Call{Call: _e.mock.On("CreateAuditLog", ctx, log)}
}

func (_c *MockAuditLogRepository_CreateAuditLog_Call) Run(run func(ctx context.Context, log *sqlentity.AuditLogs)) *MockAuditLogRepository_CreateAuditLog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlentity.AuditLogs))
	})
	return _c
}

func (_c *MockAuditLogRepository_CreateAuditLog_Call) Return(_a0 error) *MockAuditLogRepository_CreateAuditLog_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuditLogRepository_CreateAuditLog_Call) RunAndReturn(run func(context.Context, *sqlentity.AuditLogs) error) *MockAuditLogRepository_CreateAuditLog_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuditLogRepository creates a new instance of MockAuditLogRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuditLogRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuditLogRepository {
	mock := &MockAuditLogRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
