// Code generated by mockery. DO NOT EDIT.

package payslipmocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	sqlentity "github.com/JoshuaPangaribuan/payslip/internal/payslip/internal/entity/sqlentity"
)

// MockReimbursementRepository is an autogenerated mock type for the ReimbursementRepository type
type MockReimbursementRepository struct {
	mock.Mock
}

type MockReimbursementRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReimbursementRepository) EXPECT() *MockReimbursementRepository_Expecter {
	return &MockReimbursementRepository_Expecter{mock: &_m.Mock}
}

// CreateReimbursement provides a mock function with given fields: ctx, reimbursement
func (_m *MockReimbursementRepository) CreateReimbursement(ctx context.Context, reimbursement *sqlentity.ReimbursementRequests) error {
	ret := _m.Called(ctx, reimbursement)

	if len(ret) == 0 {
		panic("no return value specified for CreateReimbursement")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlentity.ReimbursementRequests) error); ok {
		r0 = rf(ctx, reimbursement)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockReimbursementRepository_CreateReimbursement_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateReimbursement'
type MockReimbursementRepository_CreateReimbursement_Call struct {
	*mock.Call
}

// CreateReimbursement is a helper method to define mock.On call
//   - ctx context.Context
//   - reimbursement *sqlentity.ReimbursementRequests
func (_e *MockReimbursementRepository_Expecter) CreateReimbursement(ctx interface{}, reimbursement interface{}) *MockReimbursementRepository_CreateReimbursement_Call {
	return &MockReimbursementRepository_CreateReimbursement_Call{Call: _e.mock.On("CreateReimbursement", ctx, reimbursement)}
}

func (_c *MockReimbursementRepository_CreateReimbursement_Call) Run(run func(ctx context.Context, reimbursement *sqlentity.ReimbursementRequests)) *MockReimbursementRepository_CreateReimbursement_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlentity.ReimbursementRequests))
	})
	return _c
}

func (_c *MockReimbursementRepository_CreateReimbursement_Call) Return(_a0 error) *MockReimbursementRepository_CreateReimbursement_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReimbursementRepository_CreateReimbursement_Call) RunAndReturn(run func(context.Context, *sqlentity.ReimbursementRequests) error) *MockReimbursementRepository_CreateReimbursement_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReimbursementRepository creates a new instance of MockReimbursementRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReimbursementRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReimbursementRepository {
	mock := &MockReimbursementRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
