// Code generated by mockery. DO NOT EDIT.

package payslipmocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	usecases "github.com/JoshuaPangaribuan/payslip/internal/payslip/internal/usecases"
)

// MockAdminPayrollSummaryUsecase is an autogenerated mock type for the AdminPayrollSummaryUsecase type
type MockAdminPayrollSummaryUsecase struct {
	mock.Mock
}

type MockAdminPayrollSummaryUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAdminPayrollSummaryUsecase) EXPECT() *MockAdminPayrollSummaryUsecase_Expecter {
	return &MockAdminPayrollSummaryUsecase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, in
func (_m *MockAdminPayrollSummaryUsecase) Execute(ctx context.Context, in usecases.AdminPayrollSummaryInput) (usecases.AdminPayrollSummaryOutput, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 usecases.AdminPayrollSummaryOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usecases.AdminPayrollSummaryInput) (usecases.AdminPayrollSummaryOutput, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usecases.AdminPayrollSummaryInput) usecases.AdminPayrollSummaryOutput); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Get(0).(usecases.AdminPayrollSummaryOutput)
	}

	if rf, ok := ret.Get(1).(func(context.Context, usecases.AdminPayrollSummaryInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdminPayrollSummaryUsecase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockAdminPayrollSummaryUsecase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - in usecases.AdminPayrollSummaryInput
func (_e *MockAdminPayrollSummaryUsecase_Expecter) Execute(ctx interface{}, in interface{}) *MockAdminPayrollSummaryUsecase_Execute_Call {
	return &MockAdminPayrollSummaryUsecase_Execute_Call{Call: _e.mock.On("Execute", ctx, in)}
}

func (_c *MockAdminPayrollSummaryUsecase_Execute_Call) Run(run func(ctx context.Context, in usecases.AdminPayrollSummaryInput)) *MockAdminPayrollSummaryUsecase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usecases.AdminPayrollSummaryInput))
	})
	return _c
}

func (_c *MockAdminPayrollSummaryUsecase_Execute_Call) Return(_a0 usecases.AdminPayrollSummaryOutput, _a1 error) *MockAdminPayrollSummaryUsecase_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdminPayrollSummaryUsecase_Execute_Call) RunAndReturn(run func(context.Context, usecases.AdminPayrollSummaryInput) (usecases.AdminPayrollSummaryOutput, error)) *MockAdminPayrollSummaryUsecase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAdminPayrollSummaryUsecase creates a new instance of MockAdminPayrollSummaryUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAdminPayrollSummaryUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAdminPayrollSummaryUsecase {
	mock := &MockAdminPayrollSummaryUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
