// Code generated by mockery. DO NOT EDIT.

package payslipmocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	sqlentity "github.com/JoshuaPangaribuan/payslip/internal/payslip/internal/entity/sqlentity"

	time "time"

	uuid "github.com/google/uuid"
)

// MockOvertimeRepository is an autogenerated mock type for the OvertimeRepository type
type MockOvertimeRepository struct {
	mock.Mock
}

type MockOvertimeRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOvertimeRepository) EXPECT() *MockOvertimeRepository_Expecter {
	return &MockOvertimeRepository_Expecter{mock: &_m.Mock}
}

// CreateOvertime provides a mock function with given fields: ctx, overtime
func (_m *MockOvertimeRepository) CreateOvertime(ctx context.Context, overtime *sqlentity.OvertimeRequests) error {
	ret := _m.Called(ctx, overtime)

	if len(ret) == 0 {
		panic("no return value specified for CreateOvertime")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlentity.OvertimeRequests) error); ok {
		r0 = rf(ctx, overtime)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOvertimeRepository_CreateOvertime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOvertime'
type MockOvertimeRepository_CreateOvertime_Call struct {
	*mock.Call
}

// CreateOvertime is a helper method to define mock.On call
//   - ctx context.Context
//   - overtime *sqlentity.OvertimeRequests
func (_e *MockOvertimeRepository_Expecter) CreateOvertime(ctx interface{}, overtime interface{}) *MockOvertimeRepository_CreateOvertime_Call {
	return &MockOvertimeRepository_CreateOvertime_Call{Call: _e.mock.On("CreateOvertime", ctx, overtime)}
}

func (_c *MockOvertimeRepository_CreateOvertime_Call) Run(run func(ctx context.Context, overtime *sqlentity.OvertimeRequests)) *MockOvertimeRepository_CreateOvertime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlentity.OvertimeRequests))
	})
	return _c
}

func (_c *MockOvertimeRepository_CreateOvertime_Call) Return(_a0 error) *MockOvertimeRepository_CreateOvertime_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOvertimeRepository_CreateOvertime_Call) RunAndReturn(run func(context.Context, *sqlentity.OvertimeRequests) error) *MockOvertimeRepository_CreateOvertime_Call {
	_c.Call.Return(run)
	return _c
}

// GetOvertimeByEmployeeAndDate provides a mock function with given fields: ctx, employeeID, date
func (_m *MockOvertimeRepository) GetOvertimeByEmployeeAndDate(ctx context.Context, employeeID uuid.UUID, date time.Time) (*sqlentity.OvertimeRequests, error) {
	ret := _m.Called(ctx, employeeID, date)

	if len(ret) == 0 {
		panic("no return value specified for GetOvertimeByEmployeeAndDate")
	}

	var r0 *sqlentity.OvertimeRequests
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) (*sqlentity.OvertimeRequests, error)); ok {
		return rf(ctx, employeeID, date)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) *sqlentity.OvertimeRequests); ok {
		r0 = rf(ctx, employeeID, date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqlentity.OvertimeRequests)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r1 = rf(ctx, employeeID, date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOvertimeRepository_GetOvertimeByEmployeeAndDate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOvertimeByEmployeeAndDate'
type MockOvertimeRepository_GetOvertimeByEmployeeAndDate_Call struct {
	*mock.Call
}

// GetOvertimeByEmployeeAndDate is a helper method to define mock.On call
//   - ctx context.Context
//   - employeeID uuid.UUID
//   - date time.Time
func (_e *MockOvertimeRepository_Expecter) GetOvertimeByEmployeeAndDate(ctx interface{}, employeeID interface{}, date interface{}) *MockOvertimeRepository_GetOvertimeByEmployeeAndDate_Call {
	return &MockOvertimeRepository_GetOvertimeByEmployeeAndDate_Call{Call: _e.mock.On("GetOvertimeByEmployeeAndDate", ctx, employeeID, date)}
}

func (_c *MockOvertimeRepository_GetOvertimeByEmployeeAndDate_Call) Run(run func(ctx context.Context, employeeID uuid.UUID, date time.Time)) *MockOvertimeRepository_GetOvertimeByEmployeeAndDate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time))
	})
	return _c
}

func (_c *MockOvertimeRepository_GetOvertimeByEmployeeAndDate_Call) Return(_a0 *sqlentity.OvertimeRequests, _a1 error) *MockOvertimeRepository_GetOvertimeByEmployeeAndDate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOvertimeRepository_GetOvertimeByEmployeeAndDate_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time) (*sqlentity.OvertimeRequests, error)) *MockOvertimeRepository_GetOvertimeByEmployeeAndDate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOvertimeRepository creates a new instance of MockOvertimeRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOvertimeRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOvertimeRepository {
	mock := &MockOvertimeRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
