// Code generated by mockery. DO NOT EDIT.

package payslipmocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	usecases "github.com/JoshuaPangaribuan/payslip/internal/payslip/internal/usecases"
)

// MockAdminRunPayrollUsecase is an autogenerated mock type for the AdminRunPayrollUsecase type
type MockAdminRunPayrollUsecase struct {
	mock.Mock
}

type MockAdminRunPayrollUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAdminRunPayrollUsecase) EXPECT() *MockAdminRunPayrollUsecase_Expecter {
	return &MockAdminRunPayrollUsecase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, in
func (_m *MockAdminRunPayrollUsecase) Execute(ctx context.Context, in usecases.AdminRunPayrollInput) (usecases.AdminRunPayrollOutput, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 usecases.AdminRunPayrollOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usecases.AdminRunPayrollInput) (usecases.AdminRunPayrollOutput, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usecases.AdminRunPayrollInput) usecases.AdminRunPayrollOutput); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Get(0).(usecases.AdminRunPayrollOutput)
	}

	if rf, ok := ret.Get(1).(func(context.Context, usecases.AdminRunPayrollInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdminRunPayrollUsecase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockAdminRunPayrollUsecase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - in usecases.AdminRunPayrollInput
func (_e *MockAdminRunPayrollUsecase_Expecter) Execute(ctx interface{}, in interface{}) *MockAdminRunPayrollUsecase_Execute_Call {
	return &MockAdminRunPayrollUsecase_Execute_Call{Call: _e.mock.On("Execute", ctx, in)}
}

func (_c *MockAdminRunPayrollUsecase_Execute_Call) Run(run func(ctx context.Context, in usecases.AdminRunPayrollInput)) *MockAdminRunPayrollUsecase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usecases.AdminRunPayrollInput))
	})
	return _c
}

func (_c *MockAdminRunPayrollUsecase_Execute_Call) Return(_a0 usecases.AdminRunPayrollOutput, _a1 error) *MockAdminRunPayrollUsecase_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdminRunPayrollUsecase_Execute_Call) RunAndReturn(run func(context.Context, usecases.AdminRunPayrollInput) (usecases.AdminRunPayrollOutput, error)) *MockAdminRunPayrollUsecase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAdminRunPayrollUsecase creates a new instance of MockAdminRunPayrollUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAdminRunPayrollUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAdminRunPayrollUsecase {
	mock := &MockAdminRunPayrollUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
