// Code generated by mockery. DO NOT EDIT.

package payslipmocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	sqlentity "github.com/JoshuaPangaribuan/payslip/internal/payslip/internal/entity/sqlentity"

	time "time"

	uuid "github.com/google/uuid"
)

// MockAttendancePeriodRepository is an autogenerated mock type for the AttendancePeriodRepository type
type MockAttendancePeriodRepository struct {
	mock.Mock
}

type MockAttendancePeriodRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAttendancePeriodRepository) EXPECT() *MockAttendancePeriodRepository_Expecter {
	return &MockAttendancePeriodRepository_Expecter{mock: &_m.Mock}
}

// CreateAttendancePeriod provides a mock function with given fields: ctx, period
func (_m *MockAttendancePeriodRepository) CreateAttendancePeriod(ctx context.Context, period *sqlentity.AttendancePeriods) error {
	ret := _m.Called(ctx, period)

	if len(ret) == 0 {
		panic("no return value specified for CreateAttendancePeriod")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlentity.AttendancePeriods) error); ok {
		r0 = rf(ctx, period)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAttendancePeriodRepository_CreateAttendancePeriod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAttendancePeriod'
type MockAttendancePeriodRepository_CreateAttendancePeriod_Call struct {
	*mock.Call
}

// CreateAttendancePeriod is a helper method to define mock.On call
//   - ctx context.Context
//   - period *sqlentity.AttendancePeriods
func (_e *MockAttendancePeriodRepository_Expecter) CreateAttendancePeriod(ctx interface{}, period interface{}) *MockAttendancePeriodRepository_CreateAttendancePeriod_Call {
	return &MockAttendancePeriodRepository_CreateAttendancePeriod_Call{Call: _e.mock.On("CreateAttendancePeriod", ctx, period)}
}

func (_c *MockAttendancePeriodRepository_CreateAttendancePeriod_Call) Run(run func(ctx context.Context, period *sqlentity.AttendancePeriods)) *MockAttendancePeriodRepository_CreateAttendancePeriod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlentity.AttendancePeriods))
	})
	return _c
}

func (_c *MockAttendancePeriodRepository_CreateAttendancePeriod_Call) Return(_a0 error) *MockAttendancePeriodRepository_CreateAttendancePeriod_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAttendancePeriodRepository_CreateAttendancePeriod_Call) RunAndReturn(run func(context.Context, *sqlentity.AttendancePeriods) error) *MockAttendancePeriodRepository_CreateAttendancePeriod_Call {
	_c.Call.Return(run)
	return _c
}

// GetAttendancePeriodByDateRange provides a mock function with given fields: ctx, startDate, endDate
func (_m *MockAttendancePeriodRepository) GetAttendancePeriodByDateRange(ctx context.Context, startDate time.Time, endDate time.Time) (*sqlentity.AttendancePeriods, error) {
	ret := _m.Called(ctx, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetAttendancePeriodByDateRange")
	}

	var r0 *sqlentity.AttendancePeriods
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) (*sqlentity.AttendancePeriods, error)); ok {
		return rf(ctx, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) *sqlentity.AttendancePeriods); ok {
		r0 = rf(ctx, startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqlentity.AttendancePeriods)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, time.Time) error); ok {
		r1 = rf(ctx, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAttendancePeriodRepository_GetAttendancePeriodByDateRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAttendancePeriodByDateRange'
type MockAttendancePeriodRepository_GetAttendancePeriodByDateRange_Call struct {
	*mock.Call
}

// GetAttendancePeriodByDateRange is a helper method to define mock.On call
//   - ctx context.Context
//   - startDate time.Time
//   - endDate time.Time
func (_e *MockAttendancePeriodRepository_Expecter) GetAttendancePeriodByDateRange(ctx interface{}, startDate interface{}, endDate interface{}) *MockAttendancePeriodRepository_GetAttendancePeriodByDateRange_Call {
	return &MockAttendancePeriodRepository_GetAttendancePeriodByDateRange_Call{Call: _e.mock.On("GetAttendancePeriodByDateRange", ctx, startDate, endDate)}
}

func (_c *MockAttendancePeriodRepository_GetAttendancePeriodByDateRange_Call) Run(run func(ctx context.Context, startDate time.Time, endDate time.Time)) *MockAttendancePeriodRepository_GetAttendancePeriodByDateRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time), args[2].(time.Time))
	})
	return _c
}

func (_c *MockAttendancePeriodRepository_GetAttendancePeriodByDateRange_Call) Return(_a0 *sqlentity.AttendancePeriods, _a1 error) *MockAttendancePeriodRepository_GetAttendancePeriodByDateRange_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAttendancePeriodRepository_GetAttendancePeriodByDateRange_Call) RunAndReturn(run func(context.Context, time.Time, time.Time) (*sqlentity.AttendancePeriods, error)) *MockAttendancePeriodRepository_GetAttendancePeriodByDateRange_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockAttendancePeriodRepository) GetByID(ctx context.Context, id uuid.UUID) (*sqlentity.AttendancePeriods, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *sqlentity.AttendancePeriods
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*sqlentity.AttendancePeriods, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *sqlentity.AttendancePeriods); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqlentity.AttendancePeriods)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAttendancePeriodRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockAttendancePeriodRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockAttendancePeriodRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockAttendancePeriodRepository_GetByID_Call {
	return &MockAttendancePeriodRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockAttendancePeriodRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockAttendancePeriodRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockAttendancePeriodRepository_GetByID_Call) Return(_a0 *sqlentity.AttendancePeriods, _a1 error) *MockAttendancePeriodRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAttendancePeriodRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*sqlentity.AttendancePeriods, error)) *MockAttendancePeriodRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAttendancePeriodRepository creates a new instance of MockAttendancePeriodRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAttendancePeriodRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAttendancePeriodRepository {
	mock := &MockAttendancePeriodRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
