// Code generated by mockery. DO NOT EDIT.

package payslipmocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	sqlentity "github.com/JoshuaPangaribuan/payslip/internal/payslip/internal/entity/sqlentity"

	time "time"
)

// MockPayslipRepository is an autogenerated mock type for the PayslipRepository type
type MockPayslipRepository struct {
	mock.Mock
}

type MockPayslipRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPayslipRepository) EXPECT() *MockPayslipRepository_Expecter {
	return &MockPayslipRepository_Expecter{mock: &_m.Mock}
}

// CreatePayslip provides a mock function with given fields: ctx, payslip
func (_m *MockPayslipRepository) CreatePayslip(ctx context.Context, payslip *sqlentity.Payslips) error {
	ret := _m.Called(ctx, payslip)

	if len(ret) == 0 {
		panic("no return value specified for CreatePayslip")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlentity.Payslips) error); ok {
		r0 = rf(ctx, payslip)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPayslipRepository_CreatePayslip_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePayslip'
type MockPayslipRepository_CreatePayslip_Call struct {
	*mock.Call
}

// CreatePayslip is a helper method to define mock.On call
//   - ctx context.Context
//   - payslip *sqlentity.Payslips
func (_e *MockPayslipRepository_Expecter) CreatePayslip(ctx interface{}, payslip interface{}) *MockPayslipRepository_CreatePayslip_Call {
	return &MockPayslipRepository_CreatePayslip_Call{Call: _e.mock.On("CreatePayslip", ctx, payslip)}
}

func (_c *MockPayslipRepository_CreatePayslip_Call) Run(run func(ctx context.Context, payslip *sqlentity.Payslips)) *MockPayslipRepository_CreatePayslip_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlentity.Payslips))
	})
	return _c
}

func (_c *MockPayslipRepository_CreatePayslip_Call) Return(_a0 error) *MockPayslipRepository_CreatePayslip_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPayslipRepository_CreatePayslip_Call) RunAndReturn(run func(context.Context, *sqlentity.Payslips) error) *MockPayslipRepository_CreatePayslip_Call {
	_c.Call.Return(run)
	return _c
}

// GetAttendanceRecordsByEmployeeAndDateRange provides a mock function with given fields: ctx, employeeID, startDate, endDate
func (_m *MockPayslipRepository) GetAttendanceRecordsByEmployeeAndDateRange(ctx context.Context, employeeID string, startDate time.Time, endDate time.Time) ([]*sqlentity.AttendanceRecords, error) {
	ret := _m.Called(ctx, employeeID, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetAttendanceRecordsByEmployeeAndDateRange")
	}

	var r0 []*sqlentity.AttendanceRecords
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) ([]*sqlentity.AttendanceRecords, error)); ok {
		return rf(ctx, employeeID, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) []*sqlentity.AttendanceRecords); ok {
		r0 = rf(ctx, employeeID, startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*sqlentity.AttendanceRecords)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time, time.Time) error); ok {
		r1 = rf(ctx, employeeID, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPayslipRepository_GetAttendanceRecordsByEmployeeAndDateRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAttendanceRecordsByEmployeeAndDateRange'
type MockPayslipRepository_GetAttendanceRecordsByEmployeeAndDateRange_Call struct {
	*mock.Call
}

// GetAttendanceRecordsByEmployeeAndDateRange is a helper method to define mock.On call
//   - ctx context.Context
//   - employeeID string
//   - startDate time.Time
//   - endDate time.Time
func (_e *MockPayslipRepository_Expecter) GetAttendanceRecordsByEmployeeAndDateRange(ctx interface{}, employeeID interface{}, startDate interface{}, endDate interface{}) *MockPayslipRepository_GetAttendanceRecordsByEmployeeAndDateRange_Call {
	return &MockPayslipRepository_GetAttendanceRecordsByEmployeeAndDateRange_Call{Call: _e.mock.On("GetAttendanceRecordsByEmployeeAndDateRange", ctx, employeeID, startDate, endDate)}
}

func (_c *MockPayslipRepository_GetAttendanceRecordsByEmployeeAndDateRange_Call) Run(run func(ctx context.Context, employeeID string, startDate time.Time, endDate time.Time)) *MockPayslipRepository_GetAttendanceRecordsByEmployeeAndDateRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time), args[3].(time.Time))
	})
	return _c
}

func (_c *MockPayslipRepository_GetAttendanceRecordsByEmployeeAndDateRange_Call) Return(_a0 []*sqlentity.AttendanceRecords, _a1 error) *MockPayslipRepository_GetAttendanceRecordsByEmployeeAndDateRange_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPayslipRepository_GetAttendanceRecordsByEmployeeAndDateRange_Call) RunAndReturn(run func(context.Context, string, time.Time, time.Time) ([]*sqlentity.AttendanceRecords, error)) *MockPayslipRepository_GetAttendanceRecordsByEmployeeAndDateRange_Call {
	_c.Call.Return(run)
	return _c
}

// GetEmployeeByID provides a mock function with given fields: ctx, id
func (_m *MockPayslipRepository) GetEmployeeByID(ctx context.Context, id string) (*sqlentity.Employees, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetEmployeeByID")
	}

	var r0 *sqlentity.Employees
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*sqlentity.Employees, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *sqlentity.Employees); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqlentity.Employees)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPayslipRepository_GetEmployeeByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEmployeeByID'
type MockPayslipRepository_GetEmployeeByID_Call struct {
	*mock.Call
}

// GetEmployeeByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockPayslipRepository_Expecter) GetEmployeeByID(ctx interface{}, id interface{}) *MockPayslipRepository_GetEmployeeByID_Call {
	return &MockPayslipRepository_GetEmployeeByID_Call{Call: _e.mock.On("GetEmployeeByID", ctx, id)}
}

func (_c *MockPayslipRepository_GetEmployeeByID_Call) Run(run func(ctx context.Context, id string)) *MockPayslipRepository_GetEmployeeByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPayslipRepository_GetEmployeeByID_Call) Return(_a0 *sqlentity.Employees, _a1 error) *MockPayslipRepository_GetEmployeeByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPayslipRepository_GetEmployeeByID_Call) RunAndReturn(run func(context.Context, string) (*sqlentity.Employees, error)) *MockPayslipRepository_GetEmployeeByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetOvertimeRequestsByEmployeeAndDateRange provides a mock function with given fields: ctx, employeeID, startDate, endDate
func (_m *MockPayslipRepository) GetOvertimeRequestsByEmployeeAndDateRange(ctx context.Context, employeeID string, startDate time.Time, endDate time.Time) ([]*sqlentity.OvertimeRequests, error) {
	ret := _m.Called(ctx, employeeID, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetOvertimeRequestsByEmployeeAndDateRange")
	}

	var r0 []*sqlentity.OvertimeRequests
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) ([]*sqlentity.OvertimeRequests, error)); ok {
		return rf(ctx, employeeID, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) []*sqlentity.OvertimeRequests); ok {
		r0 = rf(ctx, employeeID, startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*sqlentity.OvertimeRequests)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time, time.Time) error); ok {
		r1 = rf(ctx, employeeID, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPayslipRepository_GetOvertimeRequestsByEmployeeAndDateRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOvertimeRequestsByEmployeeAndDateRange'
type MockPayslipRepository_GetOvertimeRequestsByEmployeeAndDateRange_Call struct {
	*mock.Call
}

// GetOvertimeRequestsByEmployeeAndDateRange is a helper method to define mock.On call
//   - ctx context.Context
//   - employeeID string
//   - startDate time.Time
//   - endDate time.Time
func (_e *MockPayslipRepository_Expecter) GetOvertimeRequestsByEmployeeAndDateRange(ctx interface{}, employeeID interface{}, startDate interface{}, endDate interface{}) *MockPayslipRepository_GetOvertimeRequestsByEmployeeAndDateRange_Call {
	return &MockPayslipRepository_GetOvertimeRequestsByEmployeeAndDateRange_Call{Call: _e.mock.On("GetOvertimeRequestsByEmployeeAndDateRange", ctx, employeeID, startDate, endDate)}
}

func (_c *MockPayslipRepository_GetOvertimeRequestsByEmployeeAndDateRange_Call) Run(run func(ctx context.Context, employeeID string, startDate time.Time, endDate time.Time)) *MockPayslipRepository_GetOvertimeRequestsByEmployeeAndDateRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time), args[3].(time.Time))
	})
	return _c
}

func (_c *MockPayslipRepository_GetOvertimeRequestsByEmployeeAndDateRange_Call) Return(_a0 []*sqlentity.OvertimeRequests, _a1 error) *MockPayslipRepository_GetOvertimeRequestsByEmployeeAndDateRange_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPayslipRepository_GetOvertimeRequestsByEmployeeAndDateRange_Call) RunAndReturn(run func(context.Context, string, time.Time, time.Time) ([]*sqlentity.OvertimeRequests, error)) *MockPayslipRepository_GetOvertimeRequestsByEmployeeAndDateRange_Call {
	_c.Call.Return(run)
	return _c
}

// GetPayrollRunByMonthAndYear provides a mock function with given fields: ctx, month, year
func (_m *MockPayslipRepository) GetPayrollRunByMonthAndYear(ctx context.Context, month int, year int) (*sqlentity.PayrollRuns, error) {
	ret := _m.Called(ctx, month, year)

	if len(ret) == 0 {
		panic("no return value specified for GetPayrollRunByMonthAndYear")
	}

	var r0 *sqlentity.PayrollRuns
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) (*sqlentity.PayrollRuns, error)); ok {
		return rf(ctx, month, year)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) *sqlentity.PayrollRuns); ok {
		r0 = rf(ctx, month, year)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqlentity.PayrollRuns)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, month, year)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPayslipRepository_GetPayrollRunByMonthAndYear_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPayrollRunByMonthAndYear'
type MockPayslipRepository_GetPayrollRunByMonthAndYear_Call struct {
	*mock.Call
}

// GetPayrollRunByMonthAndYear is a helper method to define mock.On call
//   - ctx context.Context
//   - month int
//   - year int
func (_e *MockPayslipRepository_Expecter) GetPayrollRunByMonthAndYear(ctx interface{}, month interface{}, year interface{}) *MockPayslipRepository_GetPayrollRunByMonthAndYear_Call {
	return &MockPayslipRepository_GetPayrollRunByMonthAndYear_Call{Call: _e.mock.On("GetPayrollRunByMonthAndYear", ctx, month, year)}
}

func (_c *MockPayslipRepository_GetPayrollRunByMonthAndYear_Call) Run(run func(ctx context.Context, month int, year int)) *MockPayslipRepository_GetPayrollRunByMonthAndYear_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockPayslipRepository_GetPayrollRunByMonthAndYear_Call) Return(_a0 *sqlentity.PayrollRuns, _a1 error) *MockPayslipRepository_GetPayrollRunByMonthAndYear_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPayslipRepository_GetPayrollRunByMonthAndYear_Call) RunAndReturn(run func(context.Context, int, int) (*sqlentity.PayrollRuns, error)) *MockPayslipRepository_GetPayrollRunByMonthAndYear_Call {
	_c.Call.Return(run)
	return _c
}

// GetPayslipByEmployeeAndPeriod provides a mock function with given fields: ctx, employeeID, month, year
func (_m *MockPayslipRepository) GetPayslipByEmployeeAndPeriod(ctx context.Context, employeeID string, month int, year int) (*sqlentity.Payslips, error) {
	ret := _m.Called(ctx, employeeID, month, year)

	if len(ret) == 0 {
		panic("no return value specified for GetPayslipByEmployeeAndPeriod")
	}

	var r0 *sqlentity.Payslips
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) (*sqlentity.Payslips, error)); ok {
		return rf(ctx, employeeID, month, year)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) *sqlentity.Payslips); ok {
		r0 = rf(ctx, employeeID, month, year)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqlentity.Payslips)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = rf(ctx, employeeID, month, year)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPayslipRepository_GetPayslipByEmployeeAndPeriod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPayslipByEmployeeAndPeriod'
type MockPayslipRepository_GetPayslipByEmployeeAndPeriod_Call struct {
	*mock.Call
}

// GetPayslipByEmployeeAndPeriod is a helper method to define mock.On call
//   - ctx context.Context
//   - employeeID string
//   - month int
//   - year int
func (_e *MockPayslipRepository_Expecter) GetPayslipByEmployeeAndPeriod(ctx interface{}, employeeID interface{}, month interface{}, year interface{}) *MockPayslipRepository_GetPayslipByEmployeeAndPeriod_Call {
	return &MockPayslipRepository_GetPayslipByEmployeeAndPeriod_Call{Call: _e.mock.On("GetPayslipByEmployeeAndPeriod", ctx, employeeID, month, year)}
}

func (_c *MockPayslipRepository_GetPayslipByEmployeeAndPeriod_Call) Run(run func(ctx context.Context, employeeID string, month int, year int)) *MockPayslipRepository_GetPayslipByEmployeeAndPeriod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockPayslipRepository_GetPayslipByEmployeeAndPeriod_Call) Return(_a0 *sqlentity.Payslips, _a1 error) *MockPayslipRepository_GetPayslipByEmployeeAndPeriod_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPayslipRepository_GetPayslipByEmployeeAndPeriod_Call) RunAndReturn(run func(context.Context, string, int, int) (*sqlentity.Payslips, error)) *MockPayslipRepository_GetPayslipByEmployeeAndPeriod_Call {
	_c.Call.Return(run)
	return _c
}

// GetReimbursementRequestsByEmployeeAndDateRange provides a mock function with given fields: ctx, employeeID, startDate, endDate
func (_m *MockPayslipRepository) GetReimbursementRequestsByEmployeeAndDateRange(ctx context.Context, employeeID string, startDate time.Time, endDate time.Time) ([]*sqlentity.ReimbursementRequests, error) {
	ret := _m.Called(ctx, employeeID, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetReimbursementRequestsByEmployeeAndDateRange")
	}

	var r0 []*sqlentity.ReimbursementRequests
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) ([]*sqlentity.ReimbursementRequests, error)); ok {
		return rf(ctx, employeeID, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) []*sqlentity.ReimbursementRequests); ok {
		r0 = rf(ctx, employeeID, startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*sqlentity.ReimbursementRequests)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time, time.Time) error); ok {
		r1 = rf(ctx, employeeID, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPayslipRepository_GetReimbursementRequestsByEmployeeAndDateRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReimbursementRequestsByEmployeeAndDateRange'
type MockPayslipRepository_GetReimbursementRequestsByEmployeeAndDateRange_Call struct {
	*mock.Call
}

// GetReimbursementRequestsByEmployeeAndDateRange is a helper method to define mock.On call
//   - ctx context.Context
//   - employeeID string
//   - startDate time.Time
//   - endDate time.Time
func (_e *MockPayslipRepository_Expecter) GetReimbursementRequestsByEmployeeAndDateRange(ctx interface{}, employeeID interface{}, startDate interface{}, endDate interface{}) *MockPayslipRepository_GetReimbursementRequestsByEmployeeAndDateRange_Call {
	return &MockPayslipRepository_GetReimbursementRequestsByEmployeeAndDateRange_Call{Call: _e.mock.On("GetReimbursementRequestsByEmployeeAndDateRange", ctx, employeeID, startDate, endDate)}
}

func (_c *MockPayslipRepository_GetReimbursementRequestsByEmployeeAndDateRange_Call) Run(run func(ctx context.Context, employeeID string, startDate time.Time, endDate time.Time)) *MockPayslipRepository_GetReimbursementRequestsByEmployeeAndDateRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time), args[3].(time.Time))
	})
	return _c
}

func (_c *MockPayslipRepository_GetReimbursementRequestsByEmployeeAndDateRange_Call) Return(_a0 []*sqlentity.ReimbursementRequests, _a1 error) *MockPayslipRepository_GetReimbursementRequestsByEmployeeAndDateRange_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPayslipRepository_GetReimbursementRequestsByEmployeeAndDateRange_Call) RunAndReturn(run func(context.Context, string, time.Time, time.Time) ([]*sqlentity.ReimbursementRequests, error)) *MockPayslipRepository_GetReimbursementRequestsByEmployeeAndDateRange_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPayslipRepository creates a new instance of MockPayslipRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPayslipRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPayslipRepository {
	mock := &MockPayslipRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
