// Code generated by mockery. DO NOT EDIT.

package payslipmocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	sqlentity "github.com/JoshuaPangaribuan/payslip/internal/payslip/internal/entity/sqlentity"

	time "time"

	uuid "github.com/google/uuid"
)

// MockPayrollRepository is an autogenerated mock type for the PayrollRepository type
type MockPayrollRepository struct {
	mock.Mock
}

type MockPayrollRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPayrollRepository) EXPECT() *MockPayrollRepository_Expecter {
	return &MockPayrollRepository_Expecter{mock: &_m.Mock}
}

// CreatePayrollRun provides a mock function with given fields: ctx, payrollRun
func (_m *MockPayrollRepository) CreatePayrollRun(ctx context.Context, payrollRun *sqlentity.PayrollRuns) error {
	ret := _m.Called(ctx, payrollRun)

	if len(ret) == 0 {
		panic("no return value specified for CreatePayrollRun")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlentity.PayrollRuns) error); ok {
		r0 = rf(ctx, payrollRun)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPayrollRepository_CreatePayrollRun_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePayrollRun'
type MockPayrollRepository_CreatePayrollRun_Call struct {
	*mock.Call
}

// CreatePayrollRun is a helper method to define mock.On call
//   - ctx context.Context
//   - payrollRun *sqlentity.PayrollRuns
func (_e *MockPayrollRepository_Expecter) CreatePayrollRun(ctx interface{}, payrollRun interface{}) *MockPayrollRepository_CreatePayrollRun_Call {
	return &MockPayrollRepository_CreatePayrollRun_Call{Call: _e.mock.On("CreatePayrollRun", ctx, payrollRun)}
}

func (_c *MockPayrollRepository_CreatePayrollRun_Call) Run(run func(ctx context.Context, payrollRun *sqlentity.PayrollRuns)) *MockPayrollRepository_CreatePayrollRun_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlentity.PayrollRuns))
	})
	return _c
}

func (_c *MockPayrollRepository_CreatePayrollRun_Call) Return(_a0 error) *MockPayrollRepository_CreatePayrollRun_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPayrollRepository_CreatePayrollRun_Call) RunAndReturn(run func(context.Context, *sqlentity.PayrollRuns) error) *MockPayrollRepository_CreatePayrollRun_Call {
	_c.Call.Return(run)
	return _c
}

// GetActiveEmployees provides a mock function with given fields: ctx
func (_m *MockPayrollRepository) GetActiveEmployees(ctx context.Context) ([]*sqlentity.Employees, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveEmployees")
	}

	var r0 []*sqlentity.Employees
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*sqlentity.Employees, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*sqlentity.Employees); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*sqlentity.Employees)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPayrollRepository_GetActiveEmployees_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveEmployees'
type MockPayrollRepository_GetActiveEmployees_Call struct {
	*mock.Call
}

// GetActiveEmployees is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPayrollRepository_Expecter) GetActiveEmployees(ctx interface{}) *MockPayrollRepository_GetActiveEmployees_Call {
	return &MockPayrollRepository_GetActiveEmployees_Call{Call: _e.mock.On("GetActiveEmployees", ctx)}
}

func (_c *MockPayrollRepository_GetActiveEmployees_Call) Run(run func(ctx context.Context)) *MockPayrollRepository_GetActiveEmployees_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockPayrollRepository_GetActiveEmployees_Call) Return(_a0 []*sqlentity.Employees, _a1 error) *MockPayrollRepository_GetActiveEmployees_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPayrollRepository_GetActiveEmployees_Call) RunAndReturn(run func(context.Context) ([]*sqlentity.Employees, error)) *MockPayrollRepository_GetActiveEmployees_Call {
	_c.Call.Return(run)
	return _c
}

// GetAttendanceByPeriod provides a mock function with given fields: ctx, employeeID, startDate, endDate
func (_m *MockPayrollRepository) GetAttendanceByPeriod(ctx context.Context, employeeID uuid.UUID, startDate time.Time, endDate time.Time) ([]*sqlentity.AttendanceRecords, error) {
	ret := _m.Called(ctx, employeeID, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetAttendanceByPeriod")
	}

	var r0 []*sqlentity.AttendanceRecords
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, time.Time) ([]*sqlentity.AttendanceRecords, error)); ok {
		return rf(ctx, employeeID, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, time.Time) []*sqlentity.AttendanceRecords); ok {
		r0 = rf(ctx, employeeID, startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*sqlentity.AttendanceRecords)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time, time.Time) error); ok {
		r1 = rf(ctx, employeeID, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPayrollRepository_GetAttendanceByPeriod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAttendanceByPeriod'
type MockPayrollRepository_GetAttendanceByPeriod_Call struct {
	*mock.Call
}

// GetAttendanceByPeriod is a helper method to define mock.On call
//   - ctx context.Context
//   - employeeID uuid.UUID
//   - startDate time.Time
//   - endDate time.Time
func (_e *MockPayrollRepository_Expecter) GetAttendanceByPeriod(ctx interface{}, employeeID interface{}, startDate interface{}, endDate interface{}) *MockPayrollRepository_GetAttendanceByPeriod_Call {
	return &MockPayrollRepository_GetAttendanceByPeriod_Call{Call: _e.mock.On("GetAttendanceByPeriod", ctx, employeeID, startDate, endDate)}
}

func (_c *MockPayrollRepository_GetAttendanceByPeriod_Call) Run(run func(ctx context.Context, employeeID uuid.UUID, startDate time.Time, endDate time.Time)) *MockPayrollRepository_GetAttendanceByPeriod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time), args[3].(time.Time))
	})
	return _c
}

func (_c *MockPayrollRepository_GetAttendanceByPeriod_Call) Return(_a0 []*sqlentity.AttendanceRecords, _a1 error) *MockPayrollRepository_GetAttendanceByPeriod_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPayrollRepository_GetAttendanceByPeriod_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time, time.Time) ([]*sqlentity.AttendanceRecords, error)) *MockPayrollRepository_GetAttendanceByPeriod_Call {
	_c.Call.Return(run)
	return _c
}

// GetOvertimeByPeriod provides a mock function with given fields: ctx, employeeID, startDate, endDate
func (_m *MockPayrollRepository) GetOvertimeByPeriod(ctx context.Context, employeeID uuid.UUID, startDate time.Time, endDate time.Time) ([]*sqlentity.OvertimeRequests, error) {
	ret := _m.Called(ctx, employeeID, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetOvertimeByPeriod")
	}

	var r0 []*sqlentity.OvertimeRequests
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, time.Time) ([]*sqlentity.OvertimeRequests, error)); ok {
		return rf(ctx, employeeID, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, time.Time) []*sqlentity.OvertimeRequests); ok {
		r0 = rf(ctx, employeeID, startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*sqlentity.OvertimeRequests)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time, time.Time) error); ok {
		r1 = rf(ctx, employeeID, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPayrollRepository_GetOvertimeByPeriod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOvertimeByPeriod'
type MockPayrollRepository_GetOvertimeByPeriod_Call struct {
	*mock.Call
}

// GetOvertimeByPeriod is a helper method to define mock.On call
//   - ctx context.Context
//   - employeeID uuid.UUID
//   - startDate time.Time
//   - endDate time.Time
func (_e *MockPayrollRepository_Expecter) GetOvertimeByPeriod(ctx interface{}, employeeID interface{}, startDate interface{}, endDate interface{}) *MockPayrollRepository_GetOvertimeByPeriod_Call {
	return &MockPayrollRepository_GetOvertimeByPeriod_Call{Call: _e.mock.On("GetOvertimeByPeriod", ctx, employeeID, startDate, endDate)}
}

func (_c *MockPayrollRepository_GetOvertimeByPeriod_Call) Run(run func(ctx context.Context, employeeID uuid.UUID, startDate time.Time, endDate time.Time)) *MockPayrollRepository_GetOvertimeByPeriod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time), args[3].(time.Time))
	})
	return _c
}

func (_c *MockPayrollRepository_GetOvertimeByPeriod_Call) Return(_a0 []*sqlentity.OvertimeRequests, _a1 error) *MockPayrollRepository_GetOvertimeByPeriod_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPayrollRepository_GetOvertimeByPeriod_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time, time.Time) ([]*sqlentity.OvertimeRequests, error)) *MockPayrollRepository_GetOvertimeByPeriod_Call {
	_c.Call.Return(run)
	return _c
}

// GetPayrollRunByAttendancePeriod provides a mock function with given fields: ctx, attendancePeriodID
func (_m *MockPayrollRepository) GetPayrollRunByAttendancePeriod(ctx context.Context, attendancePeriodID uuid.UUID) (*sqlentity.PayrollRuns, error) {
	ret := _m.Called(ctx, attendancePeriodID)

	if len(ret) == 0 {
		panic("no return value specified for GetPayrollRunByAttendancePeriod")
	}

	var r0 *sqlentity.PayrollRuns
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*sqlentity.PayrollRuns, error)); ok {
		return rf(ctx, attendancePeriodID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *sqlentity.PayrollRuns); ok {
		r0 = rf(ctx, attendancePeriodID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqlentity.PayrollRuns)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, attendancePeriodID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPayrollRepository_GetPayrollRunByAttendancePeriod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPayrollRunByAttendancePeriod'
type MockPayrollRepository_GetPayrollRunByAttendancePeriod_Call struct {
	*mock.Call
}

// GetPayrollRunByAttendancePeriod is a helper method to define mock.On call
//   - ctx context.Context
//   - attendancePeriodID uuid.UUID
func (_e *MockPayrollRepository_Expecter) GetPayrollRunByAttendancePeriod(ctx interface{}, attendancePeriodID interface{}) *MockPayrollRepository_GetPayrollRunByAttendancePeriod_Call {
	return &MockPayrollRepository_GetPayrollRunByAttendancePeriod_Call{Call: _e.mock.On("GetPayrollRunByAttendancePeriod", ctx, attendancePeriodID)}
}

func (_c *MockPayrollRepository_GetPayrollRunByAttendancePeriod_Call) Run(run func(ctx context.Context, attendancePeriodID uuid.UUID)) *MockPayrollRepository_GetPayrollRunByAttendancePeriod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockPayrollRepository_GetPayrollRunByAttendancePeriod_Call) Return(_a0 *sqlentity.PayrollRuns, _a1 error) *MockPayrollRepository_GetPayrollRunByAttendancePeriod_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPayrollRepository_GetPayrollRunByAttendancePeriod_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*sqlentity.PayrollRuns, error)) *MockPayrollRepository_GetPayrollRunByAttendancePeriod_Call {
	_c.Call.Return(run)
	return _c
}

// GetReimbursementsByPeriod provides a mock function with given fields: ctx, employeeID, startDate, endDate
func (_m *MockPayrollRepository) GetReimbursementsByPeriod(ctx context.Context, employeeID uuid.UUID, startDate time.Time, endDate time.Time) ([]*sqlentity.ReimbursementRequests, error) {
	ret := _m.Called(ctx, employeeID, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetReimbursementsByPeriod")
	}

	var r0 []*sqlentity.ReimbursementRequests
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, time.Time) ([]*sqlentity.ReimbursementRequests, error)); ok {
		return rf(ctx, employeeID, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, time.Time) []*sqlentity.ReimbursementRequests); ok {
		r0 = rf(ctx, employeeID, startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*sqlentity.ReimbursementRequests)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time, time.Time) error); ok {
		r1 = rf(ctx, employeeID, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPayrollRepository_GetReimbursementsByPeriod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReimbursementsByPeriod'
type MockPayrollRepository_GetReimbursementsByPeriod_Call struct {
	*mock.Call
}

// GetReimbursementsByPeriod is a helper method to define mock.On call
//   - ctx context.Context
//   - employeeID uuid.UUID
//   - startDate time.Time
//   - endDate time.Time
func (_e *MockPayrollRepository_Expecter) GetReimbursementsByPeriod(ctx interface{}, employeeID interface{}, startDate interface{}, endDate interface{}) *MockPayrollRepository_GetReimbursementsByPeriod_Call {
	return &MockPayrollRepository_GetReimbursementsByPeriod_Call{Call: _e.mock.On("GetReimbursementsByPeriod", ctx, employeeID, startDate, endDate)}
}

func (_c *MockPayrollRepository_GetReimbursementsByPeriod_Call) Run(run func(ctx context.Context, employeeID uuid.UUID, startDate time.Time, endDate time.Time)) *MockPayrollRepository_GetReimbursementsByPeriod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time), args[3].(time.Time))
	})
	return _c
}

func (_c *MockPayrollRepository_GetReimbursementsByPeriod_Call) Return(_a0 []*sqlentity.ReimbursementRequests, _a1 error) *MockPayrollRepository_GetReimbursementsByPeriod_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPayrollRepository_GetReimbursementsByPeriod_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time, time.Time) ([]*sqlentity.ReimbursementRequests, error)) *MockPayrollRepository_GetReimbursementsByPeriod_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPayrollRepository creates a new instance of MockPayrollRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPayrollRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPayrollRepository {
	mock := &MockPayrollRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
