// Code generated by mockery. DO NOT EDIT.

package payslipmocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	usecases "github.com/JoshuaPangaribuan/payslip/internal/payslip/internal/usecases"
)

// MockEmployeeSubmitReimbursementUsecase is an autogenerated mock type for the EmployeeSubmitReimbursementUsecase type
type MockEmployeeSubmitReimbursementUsecase struct {
	mock.Mock
}

type MockEmployeeSubmitReimbursementUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEmployeeSubmitReimbursementUsecase) EXPECT() *MockEmployeeSubmitReimbursementUsecase_Expecter {
	return &MockEmployeeSubmitReimbursementUsecase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, in
func (_m *MockEmployeeSubmitReimbursementUsecase) Execute(ctx context.Context, in usecases.EmployeeSubmitReimbursementInput) (usecases.EmployeeSubmitReimbursementOutput, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 usecases.EmployeeSubmitReimbursementOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usecases.EmployeeSubmitReimbursementInput) (usecases.EmployeeSubmitReimbursementOutput, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usecases.EmployeeSubmitReimbursementInput) usecases.EmployeeSubmitReimbursementOutput); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Get(0).(usecases.EmployeeSubmitReimbursementOutput)
	}

	if rf, ok := ret.Get(1).(func(context.Context, usecases.EmployeeSubmitReimbursementInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEmployeeSubmitReimbursementUsecase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockEmployeeSubmitReimbursementUsecase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - in usecases.EmployeeSubmitReimbursementInput
func (_e *MockEmployeeSubmitReimbursementUsecase_Expecter) Execute(ctx interface{}, in interface{}) *MockEmployeeSubmitReimbursementUsecase_Execute_Call {
	return &MockEmployeeSubmitReimbursementUsecase_Execute_Call{Call: _e.mock.On("Execute", ctx, in)}
}

func (_c *MockEmployeeSubmitReimbursementUsecase_Execute_Call) Run(run func(ctx context.Context, in usecases.EmployeeSubmitReimbursementInput)) *MockEmployeeSubmitReimbursementUsecase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usecases.EmployeeSubmitReimbursementInput))
	})
	return _c
}

func (_c *MockEmployeeSubmitReimbursementUsecase_Execute_Call) Return(_a0 usecases.EmployeeSubmitReimbursementOutput, _a1 error) *MockEmployeeSubmitReimbursementUsecase_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEmployeeSubmitReimbursementUsecase_Execute_Call) RunAndReturn(run func(context.Context, usecases.EmployeeSubmitReimbursementInput) (usecases.EmployeeSubmitReimbursementOutput, error)) *MockEmployeeSubmitReimbursementUsecase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEmployeeSubmitReimbursementUsecase creates a new instance of MockEmployeeSubmitReimbursementUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmployeeSubmitReimbursementUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmployeeSubmitReimbursementUsecase {
	mock := &MockEmployeeSubmitReimbursementUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
