// Code generated by mockery. DO NOT EDIT.

package payslipmocks

import (
	context "context"

	usecases "github.com/JoshuaPangaribuan/payslip/internal/payslip/internal/usecases"
	mock "github.com/stretchr/testify/mock"
)

// MockEmployeeSubmitOvertimeUsecase is an autogenerated mock type for the EmployeeSubmitOvertimeUsecase type
type MockEmployeeSubmitOvertimeUsecase struct {
	mock.Mock
}

type MockEmployeeSubmitOvertimeUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEmployeeSubmitOvertimeUsecase) EXPECT() *MockEmployeeSubmitOvertimeUsecase_Expecter {
	return &MockEmployeeSubmitOvertimeUsecase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, input
func (_m *MockEmployeeSubmitOvertimeUsecase) Execute(ctx context.Context, input usecases.EmployeeSubmitOvertimeInput) (usecases.EmployeeSubmitOvertimeOutput, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 usecases.EmployeeSubmitOvertimeOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usecases.EmployeeSubmitOvertimeInput) (usecases.EmployeeSubmitOvertimeOutput, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usecases.EmployeeSubmitOvertimeInput) usecases.EmployeeSubmitOvertimeOutput); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(usecases.EmployeeSubmitOvertimeOutput)
	}

	if rf, ok := ret.Get(1).(func(context.Context, usecases.EmployeeSubmitOvertimeInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEmployeeSubmitOvertimeUsecase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockEmployeeSubmitOvertimeUsecase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - input usecases.EmployeeSubmitOvertimeInput
func (_e *MockEmployeeSubmitOvertimeUsecase_Expecter) Execute(ctx interface{}, input interface{}) *MockEmployeeSubmitOvertimeUsecase_Execute_Call {
	return &MockEmployeeSubmitOvertimeUsecase_Execute_Call{Call: _e.mock.On("Execute", ctx, input)}
}

func (_c *MockEmployeeSubmitOvertimeUsecase_Execute_Call) Run(run func(ctx context.Context, input usecases.EmployeeSubmitOvertimeInput)) *MockEmployeeSubmitOvertimeUsecase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usecases.EmployeeSubmitOvertimeInput))
	})
	return _c
}

func (_c *MockEmployeeSubmitOvertimeUsecase_Execute_Call) Return(_a0 usecases.EmployeeSubmitOvertimeOutput, _a1 error) *MockEmployeeSubmitOvertimeUsecase_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEmployeeSubmitOvertimeUsecase_Execute_Call) RunAndReturn(run func(context.Context, usecases.EmployeeSubmitOvertimeInput) (usecases.EmployeeSubmitOvertimeOutput, error)) *MockEmployeeSubmitOvertimeUsecase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEmployeeSubmitOvertimeUsecase creates a new instance of MockEmployeeSubmitOvertimeUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmployeeSubmitOvertimeUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmployeeSubmitOvertimeUsecase {
	mock := &MockEmployeeSubmitOvertimeUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
