// Code generated by mockery. DO NOT EDIT.

package payslipmocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	usecases "github.com/JoshuaPangaribuan/payslip/internal/payslip/internal/usecases"
)

// MockEmployeeSubmitAttendanceUsecase is an autogenerated mock type for the EmployeeSubmitAttendanceUsecase type
type MockEmployeeSubmitAttendanceUsecase struct {
	mock.Mock
}

type MockEmployeeSubmitAttendanceUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEmployeeSubmitAttendanceUsecase) EXPECT() *MockEmployeeSubmitAttendanceUsecase_Expecter {
	return &MockEmployeeSubmitAttendanceUsecase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, in
func (_m *MockEmployeeSubmitAttendanceUsecase) Execute(ctx context.Context, in usecases.EmployeeSubmitAttendanceInput) (usecases.EmployeeSubmitAttendanceOutput, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 usecases.EmployeeSubmitAttendanceOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usecases.EmployeeSubmitAttendanceInput) (usecases.EmployeeSubmitAttendanceOutput, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usecases.EmployeeSubmitAttendanceInput) usecases.EmployeeSubmitAttendanceOutput); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Get(0).(usecases.EmployeeSubmitAttendanceOutput)
	}

	if rf, ok := ret.Get(1).(func(context.Context, usecases.EmployeeSubmitAttendanceInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEmployeeSubmitAttendanceUsecase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockEmployeeSubmitAttendanceUsecase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - in usecases.EmployeeSubmitAttendanceInput
func (_e *MockEmployeeSubmitAttendanceUsecase_Expecter) Execute(ctx interface{}, in interface{}) *MockEmployeeSubmitAttendanceUsecase_Execute_Call {
	return &MockEmployeeSubmitAttendanceUsecase_Execute_Call{Call: _e.mock.On("Execute", ctx, in)}
}

func (_c *MockEmployeeSubmitAttendanceUsecase_Execute_Call) Run(run func(ctx context.Context, in usecases.EmployeeSubmitAttendanceInput)) *MockEmployeeSubmitAttendanceUsecase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usecases.EmployeeSubmitAttendanceInput))
	})
	return _c
}

func (_c *MockEmployeeSubmitAttendanceUsecase_Execute_Call) Return(_a0 usecases.EmployeeSubmitAttendanceOutput, _a1 error) *MockEmployeeSubmitAttendanceUsecase_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEmployeeSubmitAttendanceUsecase_Execute_Call) RunAndReturn(run func(context.Context, usecases.EmployeeSubmitAttendanceInput) (usecases.EmployeeSubmitAttendanceOutput, error)) *MockEmployeeSubmitAttendanceUsecase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEmployeeSubmitAttendanceUsecase creates a new instance of MockEmployeeSubmitAttendanceUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmployeeSubmitAttendanceUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmployeeSubmitAttendanceUsecase {
	mock := &MockEmployeeSubmitAttendanceUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
